FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .
COPY backend/ backend/
COPY MLRepo/models/ MLRepo/models/
COPY MLRepo/src/ MLRepo/src/

RUN pip install --no-cache-dir . joblib scikit-learn pandas

EXPOSE 8000

CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
