"""Data schemas — Pydantic models for core domain entities."""

from datetime import datetime
from pydantic import BaseModel


class UserState(BaseModel):
    """Represents the current state of a user in the system."""

    user_id: str
    is_banked: bool = False
    helpyy_enabled: bool = False
    current_agent: str | None = None
    score_status: str = "unknown"  # unknown | pending | approved | rejected | pendiente_mejora
    created_at: datetime | None = None


class ChatMessage(BaseModel):
    """A single chat message."""

    session_id: str
    role: str           # "user" | "assistant" | "system"
    content: str
    agent_name: str | None = None
    timestamp: datetime | None = None


class Notification(BaseModel):
    """Notification generated by the monitor agent."""

    notification_id: str
    user_id: str
    type: str           # score_improved | score_same | score_decreased | mission_reminder
    title: str
    body: str
    created_at: datetime
    read: bool = False
    action_url: str | None = None


class Mission(BaseModel):
    """A gamification mission for financial improvement."""

    mission_id: str
    user_id: str
    name: str
    description: str
    points: int
    status: str = "active"  # locked | active | completed
    progress: float = 0.0   # 0.0 - 1.0
    target_factor: str       # ML feature this mission aims to improve
