"""Agent 3: Persistent Monitor — background service that checks scores and notifies users.

NOT user-facing. Runs as a cron/scheduler service:
  - Local: APScheduler with configurable interval (MONITOR_INTERVAL_HOURS)
  - Production: AWS EventBridge + Lambda

Each cycle:
  1. Queries users with score_status == "pendiente_mejora"
  2. Calls ML service to get current p_default
  3. Compares with previous score
  4. Generates typed notification (improved / same / decreased / mission_reminder)
  5. Stores notification for retrieval via GET /api/v1/notifications/{user_id}
"""

from __future__ import annotations

import logging
import os
import uuid
from datetime import datetime, timezone
from typing import Protocol

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

# -----------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------

MONITOR_INTERVAL_HOURS = float(os.getenv("MONITOR_INTERVAL_HOURS", "6"))

# Score change thresholds
_IMPROVEMENT_THRESHOLD = 0.02   # p_default dropped by >= 2pp → "improved"
_DECREASE_THRESHOLD = 0.02      # p_default rose by >= 2pp → "decreased"

# -----------------------------------------------------------------------
# System prompt (for notification text generation via LLM)
# -----------------------------------------------------------------------

from backend.agents.prompt_loader import load_prompt

_SYSTEM_PROMPT = load_prompt("persistent_monitor")


# -----------------------------------------------------------------------
# Notification model
# -----------------------------------------------------------------------

class Notification(BaseModel):
    """A notification generated by the monitor agent."""
    notification_id: str = Field(default_factory=lambda: f"notif_{uuid.uuid4().hex[:8]}")
    user_id: str
    type: str  # score_improved | score_same | score_decreased | mission_reminder
    title: str
    body: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    read: bool = False
    action_url: str | None = None


# -----------------------------------------------------------------------
# Notification store (in-memory for local, DynamoDB adapter for prod)
# -----------------------------------------------------------------------

class NotificationStore:
    """In-memory notification store. Swap for DynamoDB in production."""

    def __init__(self) -> None:
        self._store: dict[str, list[Notification]] = {}

    def save(self, notification: Notification) -> None:
        self._store.setdefault(notification.user_id, []).append(notification)

    def get_for_user(self, user_id: str, unread_only: bool = False) -> list[Notification]:
        notifications = self._store.get(user_id, [])
        if unread_only:
            notifications = [n for n in notifications if not n.read]
        return sorted(notifications, key=lambda n: n.created_at, reverse=True)

    def mark_read(self, notification_id: str) -> bool:
        for notifications in self._store.values():
            for n in notifications:
                if n.notification_id == notification_id:
                    n.read = True
                    return True
        return False

    def count_unread(self, user_id: str) -> int:
        return len([n for n in self._store.get(user_id, []) if not n.read])

    def clear(self) -> None:
        self._store.clear()


# Singleton for the app
_default_store = NotificationStore()


def get_notification_store() -> NotificationStore:
    return _default_store


# -----------------------------------------------------------------------
# User store protocol (what the monitor needs from the DB layer)
# -----------------------------------------------------------------------

class UserRecord(BaseModel):
    """Minimal user record the monitor needs."""
    user_id: str
    score_status: str = "pendiente_mejora"
    last_p_default: float | None = None
    occupation: str = "informal"
    declared_income: float = 1_000_000
    is_banked: bool = True
    active_missions: list[str] = Field(default_factory=list)


class UserStore(Protocol):
    """Protocol for user data access — implemented by DB layer or test mocks."""

    async def get_pending_users(self) -> list[UserRecord]: ...
    async def update_score(self, user_id: str, p_default: float, score_status: str) -> None: ...


class InMemoryUserStore:
    """In-memory user store for local development and testing."""

    def __init__(self) -> None:
        self._users: dict[str, UserRecord] = {}

    def add_user(self, user: UserRecord) -> None:
        self._users[user.user_id] = user

    async def get_pending_users(self) -> list[UserRecord]:
        return [u for u in self._users.values() if u.score_status == "pendiente_mejora"]

    async def update_score(self, user_id: str, p_default: float, score_status: str) -> None:
        if user_id in self._users:
            self._users[user_id].last_p_default = p_default
            self._users[user_id].score_status = score_status


# -----------------------------------------------------------------------
# Notification generators (pure functions)
# -----------------------------------------------------------------------

def generate_notification(
    user: UserRecord,
    new_p_default: float,
    eligible: bool,
) -> Notification:
    """Generate the right notification based on score change.

    Args:
        user: the user record with last_p_default
        new_p_default: freshly computed p_default from ML
        eligible: whether the user now qualifies for credit

    Returns:
        Notification with appropriate type, title, and body.
    """
    old_p = user.last_p_default
    delta = _compute_delta(old_p, new_p_default)
    notif_type = _classify_change(delta, eligible)

    title, body = _NOTIFICATION_TEMPLATES[notif_type](user, new_p_default, delta, eligible)

    return Notification(
        user_id=user.user_id,
        type=notif_type,
        title=title,
        body=body,
        action_url="/helpyy/advisor" if notif_type != "score_decreased" else "/helpyy/tips",
    )


def generate_mission_reminder(user: UserRecord, mission_name: str) -> Notification:
    """Generate a mission reminder notification."""
    return Notification(
        user_id=user.user_id,
        type="mission_reminder",
        title=f"No olvides tu misión: {mission_name}",
        body=f"Tienes una misión activa: {mission_name}. "
             "Cada paso que das te acerca más a tu meta crediticia.",
        action_url="/helpyy/missions",
    )


def _compute_delta(old_p: float | None, new_p: float) -> float:
    """Compute change in p_default. Negative = improvement (lower risk)."""
    if old_p is None:
        return 0.0  # first check, no delta
    return new_p - old_p


def _classify_change(delta: float, eligible: bool) -> str:
    """Classify the score change into a notification type."""
    if eligible:
        return "score_improved"  # now eligible = always treat as improved
    if delta <= -_IMPROVEMENT_THRESHOLD:
        return "score_improved"
    if delta >= _DECREASE_THRESHOLD:
        return "score_decreased"
    return "score_same"


# Notification text templates
def _improved_text(user: UserRecord, p: float, delta: float, eligible: bool) -> tuple[str, str]:
    if eligible:
        return (
            "Ya calificas para un microcrédito!",
            "Tu perfil crediticio ha mejorado lo suficiente. "
            "Entra a Helpyy Hand para ver tus opciones de crédito.",
        )
    pct = abs(delta) * 100
    return (
        "Tu perfil crediticio está mejorando",
        f"Tu riesgo bajó {pct:.1f} puntos. Sigue así — "
        "cada paso que das te acerca más a tu meta.",
    )


def _same_text(user: UserRecord, p: float, delta: float, eligible: bool) -> tuple[str, str]:
    return (
        "Tip financiero del día",
        "Tu perfil se mantiene estable. Recuerda: depositar tus ingresos "
        "en tu cuenta y pagar a tiempo son las acciones que más impactan. "
        "¿Ya completaste tus misiones de esta semana?",
    )


def _decreased_text(user: UserRecord, p: float, delta: float, eligible: bool) -> tuple[str, str]:
    return (
        "Atención: revisa tus finanzas",
        "Notamos que tu perfil crediticio bajó un poco. "
        "No te preocupes — habla con tu asesor financiero para "
        "retomar el camino. Recuerda: lo importante es la constancia.",
    )


_NOTIFICATION_TEMPLATES = {
    "score_improved": _improved_text,
    "score_same": _same_text,
    "score_decreased": _decreased_text,
}


# -----------------------------------------------------------------------
# PersistentMonitorAgent
# -----------------------------------------------------------------------

class PersistentMonitorAgent:
    """Background monitor that checks ML scores and generates notifications.

    Not a BaseAgent subclass — this is a service, not a conversational agent.
    It doesn't process user messages; it runs periodic monitoring cycles.
    """

    name = "persistent_monitor"

    def __init__(
        self,
        ml_client=None,
        user_store: UserStore | None = None,
        notification_store: NotificationStore | None = None,
    ):
        self._ml_client = ml_client
        self._user_store = user_store or InMemoryUserStore()
        self._notification_store = notification_store or get_notification_store()

    @property
    def user_store(self) -> UserStore:
        return self._user_store

    @property
    def notification_store(self) -> NotificationStore:
        return self._notification_store

    async def run_cycle(self) -> list[Notification]:
        """Execute one full monitoring cycle.

        1. Get all users with score_status == "pendiente_mejora"
        2. For each user, query ML service
        3. Compare scores, generate notifications
        4. Store notifications and update user records

        Returns list of generated notifications.
        """
        pending_users = await self._user_store.get_pending_users()
        notifications: list[Notification] = []

        logger.info("Monitor cycle: checking %d pending users", len(pending_users))

        for user in pending_users:
            try:
                notif = await self._check_user(user)
                if notif:
                    notifications.append(notif)
            except Exception:
                logger.exception("Error checking user %s", user.user_id)
                continue

        # Also generate mission reminders for users with active missions
        for user in pending_users:
            for mission_name in user.active_missions:
                reminder = generate_mission_reminder(user, mission_name)
                self._notification_store.save(reminder)
                notifications.append(reminder)

        logger.info("Monitor cycle complete: %d notifications generated", len(notifications))
        return notifications

    async def _check_user(self, user: UserRecord) -> Notification | None:
        """Check a single user's score and generate notification if needed."""
        prediction = await self._get_prediction(user)
        if prediction is None:
            return None

        new_p_default = prediction["p_default"]
        eligible = prediction["eligible"]

        # Generate notification
        notif = generate_notification(user, new_p_default, eligible)
        self._notification_store.save(notif)

        # Update user record
        new_status = "approved" if eligible else "pendiente_mejora"
        await self._user_store.update_score(user.user_id, new_p_default, new_status)

        return notif

    async def _get_prediction(self, user: UserRecord) -> dict | None:
        """Get ML prediction for a user."""
        if self._ml_client:
            from backend.ml_client.schemas import RiskRequest
            request = RiskRequest(
                declared_income=user.declared_income,
                is_banked=1 if user.is_banked else 0,
                employment_type="informal",
                age=30,
                city_type="urban",
                total_sessions=0,
                pct_conversion=0.0,
                tx_income_pct=0.0,
                payments_count=0,
                on_time_rate=0.5,
                overdue_rate=0.0,
                avg_decision_score=0.5,
            )
            pred = await self._ml_client.predict(request)
            return {
                "eligible": pred.eligible,
                "p_default": pred.p_default,
                "score_band": pred.score_band.value,
                "max_amount": pred.max_amount,
            }

        # Mock fallback: simulate based on income
        income = user.declared_income
        eligible = income >= 1_200_000
        p_default = max(0.05, 0.7 - (income / 3_000_000))
        return {
            "eligible": eligible,
            "p_default": round(p_default, 4),
            "score_band": "low_risk" if eligible else "high_risk",
            "max_amount": min(income * 2, 2_000_000) if eligible else None,
        }


# -----------------------------------------------------------------------
# Scheduler setup (local development)
# -----------------------------------------------------------------------

_scheduler = None


def start_scheduler(monitor: PersistentMonitorAgent | None = None) -> None:
    """Start APScheduler for local development.

    In production, this is replaced by EventBridge + Lambda.
    """
    global _scheduler

    if _scheduler is not None:
        return  # already running

    try:
        from apscheduler.schedulers.asyncio import AsyncIOScheduler
    except ImportError:
        logger.warning("APScheduler not installed — monitor scheduler disabled")
        return

    if monitor is None:
        monitor = PersistentMonitorAgent()

    _scheduler = AsyncIOScheduler()
    _scheduler.add_job(
        monitor.run_cycle,
        "interval",
        hours=MONITOR_INTERVAL_HOURS,
        id="monitor_cycle",
        name="Helpyy Monitor Cycle",
    )
    _scheduler.start()
    logger.info("Monitor scheduler started (interval: %.1f hours)", MONITOR_INTERVAL_HOURS)


def stop_scheduler() -> None:
    """Stop the scheduler gracefully."""
    global _scheduler
    if _scheduler is not None:
        _scheduler.shutdown(wait=False)
        _scheduler = None
        logger.info("Monitor scheduler stopped")
